### PR TITLE
chore: add testing using plenary and linting using luacheck

### PR DESCRIPTION
**Pull request by sp3ctum**
This PR adds testing and linting to the codebase. I think having tests will be a very good idea and will make collaboration much easier in the future. I don't feel that strongly about linting, but it was very easy to add so I figured why not 😄 

The testing and linting setup is copied and adapted from https://github.com/S1M0N38/my-awesome-plugin.nvim, a project template for neovim plugin development.

<details><summary>Successful tests in the terminal</summary>
<p>

Here's how the testing and linting looks like on my computer:
image

</p>
</details> 

<details><summary>Failed tests in the terminal</summary>
<p>

image

</p>
</details> 

The tests can also be run inside neovim (probably more convenient). Here's some examples:

<details><summary>Successful tests in neovim</summary>
<p>
(ignore the warnings, I haven't looked into how to get rid of them yet)
image

</p>
</details> 

<details><summary>Failed tests in neovim</summary>
<p>
 (can probably look a bit better if configured correctly)
image

</p>
</details> 

You can see an example CI run from [this commit](https://github.com/sp3ctum/tshjkl.nvim/commit/50b7691e9e28c00320d6c3962d877771e15136c7) (follow the ✅  icon to see the builds).

---

Here's some ideas for future work:
- [ ] document how to install dependencies for development (opened a PR for this https://github.com/S1M0N38/my-awesome-plugin.nvim/issues/3)
- [ ] this project could also use some instructions on how to run the tests and linting locally. Where do you think would be a good place to put this?

### CODE REVIEW

**Review by gsuuon — CHANGES_REQUESTED** [review]
Thanks for getting this going! Just got a few comments:

- Looks like there's a dupe of `.github/workflows` in project root
- Luacheck looks pretty unmaintained, [selene](https://github.com/Kampfkarren/selene) would be better (it would also be fewer dev dependencies since we already need cargo for stylua)
  - [null-ls](https://github.com/jose-elias-alvarez/null-ls.nvim) has an example of how to use it (look at selene.toml and vim.toml)
  - gha: [NTBBloodbath/selene-action](https://github.com/NTBBloodbath/selene-action)
 - This repo doesn't get many issues so let's hold off on the issue templates for now 
 - Testing setup options doesn't add a lot of value but will increase maintenance. The logic in both trail.lua and nav.lua could use some testing though! We can add a couple tests for those or just leave the test file empty here and tackle those later

**Comment by sp3ctum** [comment]
All those comments have now been addressed.
Really appreciate the suggestions; as someone new to lua, they all make sense and are really valuable to me.

I added them as separate commits to make reviewing the changes easier. Let me know if you would like me to squash them.

**Comment by gsuuon** [comment]
Thanks! A couple last comments:
- we don't need `.luacheckrc` anymore
- the `init` rule in the makefile is just for scaffolding projects based on that template, lets remove it to reduce confusion since it's not `init`ing anything in this project

I'll get this merged after your updates

**Comment by sp3ctum** [comment]
Oops, you were right. `.luacheckrc` has now been removed, and `make init` has also been removed.

I pushed these changes, but after that I also squashed and separated the changes in this PR into 2 commits. I wanted to make it easy to review the most recent changes while also getting a cleaner history after merging, but looks like my force push made it so that the separate changes aren't visible in this PR as separate commits somehow.

Well, I hope they will still be easy to see since the PR is small.

**Review by gsuuon — APPROVED** [review]
Thanks! No worries about the clean commits. I appreciate the thought, it does help with reviewing.

**Pull request merged**
